workflows:
  build-android:
    name: Build Ionic Capacitor Android
    environment:
      node: latest
      java: latest

    scripts:
      - name: Install dependencies
        script: |
          cd velorent-app
          npm install
          npm install -g @ionic/cli

      - name: Build Ionic app
        script: |
          cd velorent-app
          ionic build

      - name: Capacitor sync
        script: |
          cd velorent-app
          npx cap sync android

      - name: Give gradlew permission
        script: |
          cd velorent-app/android
          chmod +x gradlew

      - name: Build Android release APK
        script: |
          cd velorent-app/android
          ./gradlew assembleRelease

    artifacts:
      - velorent-app/android/app/build/outputs/apk/release/*.apk
