workflows:
  build-ionic-capacitor-android:
    name: Build Ionic Capacitor Android
    max_build_duration: 120
    environment:
      flutter: stable
      node: 18.18.0
      xcode: latest
      java: 17
      android_signing:
        - keystore: $CM_KEYSTORE          # uploaded in Code Signing
          keystore_password: $CM_KEYSTORE_PASSWORD
          key_alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD

    scripts:
      - name: Install dependencies
        script: |
          cd velorent-app
          npm install
          npm install -g @ionic/cli

      - name: Ionic build
        script: |
          cd velorent-app
          ionic build --prod

      - name: Capacitor sync
        script: |
          cd velorent-app
          npx cap sync android

      - name: Give gradlew permission
        script: |
          cd velorent-app/android
          chmod +x ./gradlew

      - name: Build Android universal APK
        script: |
          cd velorent-app/android
          ./gradlew assembleRelease -PcdvEnableUniversalApk=true

      - name: Sign the APK (manual signing)
        script: |
          APK_PATH=velorent-app/android/app/build/outputs/apk/release/app-release-universal.apk
          echo "Signing APK at: $APK_PATH"

          jarsigner -verbose \
            -sigalg SHA256withRSA \
            -digestalg SHA-256 \
            -keystore $CM_KEYSTORE \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            $APK_PATH \
            $CM_KEY_ALIAS

      - name: Zipalign (recommended)
        script: |
          cd velorent-app/android/app/build/outputs/apk/release
          ${ANDROID_HOME}/build-tools/34.0.0/zipalign -v 4 \
            app-release-universal.apk \
            velorent-release.apk

    artifacts:
      - velorent-app/android/app/build/outputs/apk/release/app-release-universal.apk
      - velorent-app/android/app/build/outputs/apk/release/velorent-release.apk

    publishing:
      email:
        recipients:
          - $CM_EMAIL
