workflows:
  build-ionic-capacitor-android:
    name: Build Ionic Capacitor Android
    max_build_duration: 120
    environment:
      flutter: stable
      node: 18.18.0
      xcode: latest
      java: 17
      android_signing:
        - codemagic: potito  # Use the uploaded signing config in Codemagic

    scripts:
      - name: Install dependencies
        script: |
          cd velorent-app
          npm install
          npm install -g @ionic/cli

      - name: Ionic build
        script: |
          cd velorent-app
          ionic build --prod

      - name: Capacitor sync
        script: |
          cd velorent-app
          npx cap sync android

      - name: Give gradlew permission
        script: |
          cd velorent-app/android
          chmod +x ./gradlew

      - name: Build Android universal APK
        script: |
          cd velorent-app/android
          ./gradlew assembleRelease -PcdvEnableUniversalApk=true

    artifacts:
      - velorent-app/android/app/build/outputs/apk/release/app-release-universal.apk
